### ISSUE TITLE
Gas line to fireplace

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Vacation_Rental#1]
Hi @rvzenteno Can you add a gas line out to the outdoor fireplace?

Thanks.

**Comment by rvzenteno** [comment]
Hey @theoryshaw. 

Gas was not part of my estimate but I can incorporate it.

Where is the Gas line coming into the building?
What are the BTU requirements of the Kitchen and Furnace?
Also the Grill BTU


> From Previews Email.
> Yes, you can place the water heater in the basement. 
> Gas appliances will be..
>     water heater
>     kitchen stove
>     furnace

**Comment by theoryshaw** [comment]
@shree6984 Do you know the BTU requirements for the furnace?

I'm going to the site today.  Will locate/size the gas line. 

Will get you the BTUs requirements for the others tomorrow. 

Thanks, Ryan

**Comment by shree6984** [comment]
@theoryshaw @rvzenteno  We need 80,000 BTU/hr capacity. For ref pls take a look at 
![image](https://cloud.githubusercontent.com/assets/23243475/25563971/0a2a5544-2dc6-11e7-9fe6-520d6125cccc.png)

**Comment by theoryshaw** [comment]
- BTUs
  - Range: 50k - 60k BTU
  - Firepit: 60k - 80k BTU


Gas line location...

![the downtowner_arch](https://cloud.githubusercontent.com/assets/507113/25565086/477c89a2-2d86-11e7-9a6b-9df7605b4a40.jpg)

**Comment by rvzenteno** [comment]
Ok, Here is the total BTU's I've calculated for this project:

Range = 60k BTU
Firepit = 80k BTU
Furnace = 80k BTU
WH = 70k BTU

Total BTU = 290k

**Comment by theoryshaw** [comment]
looks great. Thanks.
