### ISSUE TITLE
reroute basement duct...

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Vacation_Rental#10]
Can we reroute ductwork similar to this?  Want to make sure we put registers at glazing...
![image](https://cloud.githubusercontent.com/assets/507113/25584938/b795d77a-2e5d-11e7-9bc2-89be61597a46.png)

**Comment by shree6984** [comment]
Same issue of condensation during cooling mode. Should avoid throwing air on glazing

**Comment by theoryshaw** [comment]
At this location, they wouldn't be pointed at the glazing...

conceptually was thinking it would just do this...

![image](https://cloud.githubusercontent.com/assets/507113/25586884/06e0b9ae-2e67-11e7-994d-9654a4a77a9f.png)

**Comment by shree6984** [comment]
Yes done..
