### ISSUE TITLE
pull main supply down?

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Vacation_Rental#11]
![image](https://cloud.githubusercontent.com/assets/507113/25585107/a4cadc7a-2e5e-11e7-9690-369b664dba9a.png)

**Comment by shree6984** [comment]
The actual height of the duct will be decided by the furnace & evaporator coil.

**Comment by theoryshaw** [comment]
can you provide a suggested spec for the furnace & coil?

**Comment by shree6984** [comment]
Yes .. will provide with pdf set today

**Comment by shree6984** [comment]
If any issues then we can try placing furnace horizontal

**Comment by theoryshaw** [comment]
With the low head heights, it looks like a horizontal one, would be better. Defer to you.

**Comment by shree6984** [comment]
Yes I agree.. We will reduce duct size and submit for permit. Once equipment is finalized or contractor on board we can change orientation & update in construction drawings

**Comment by shree6984** [comment]
Solved
