### ISSUE TITLE
relocate duct above beams

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Vacation_Rental#13]
![image](https://cloud.githubusercontent.com/assets/507113/25585254/47c872f2-2e5f-11e7-84d3-4b5f2416ffe5.png)

**Comment by shree6984** [comment]
If we have grills towards storefront then in cooling mode we see condensation on glass

**Comment by theoryshaw** [comment]
There are a lot of precedents, however, for doing it this way in Wisconsin.

**Comment by shree6984** [comment]
Sure. We have updated
