### ISSUE TITLE
can we remove the 'bend' in these return?

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Vacation_Rental#14]
can we remove the 'bend' in these return?

Something like this?...

![image](https://cloud.githubusercontent.com/assets/507113/25585412/fd3cb6fc-2e5f-11e7-925f-4b03298e524c.png)

**Comment by shree6984** [comment]
We are planning to add grill on this duct for return . Or we can go for perforated duct ..

**Comment by theoryshaw** [comment]
I like the perforated duct idea.  Can you provide a percent open and area you'd need?

**Comment by shree6984** [comment]
Free area req for 2nd floor return duct - 2.8 sq fts
Free area req for 2nd floor return duct - 2.5 sq fts
