### ISSUE TITLE
 folder to put all the PDFs for permit.

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Vacation_Rental#18]
@rvzenteno @shree6984 

We can use the following folder to put all the PDFs for permit...

Vacation_Rental/Transfer/20170503 ----- ISSUE FOR PERMIT ------/

Thanks.

**Comment by shree6984** [comment]
done

**Comment by theoryshaw** [comment]
@shree6984 @rvzenteno @apbock

Thanks Guys for the help! Nice work.

If curious, here's the entire set: https://github.com/OpeningDesign/Vacation_Rental/blob/68d6be879a9bfe30b4c7d2cafb027d01b154ddcb/Transfer/20170503%20-----%20ISSUE%20FOR%20PERMIT%20------/20170503%20-%20THE%20DOWNTOWNER%20-%20ISSUE%20FOR%20PERMIT%20-%20BINDER%20SET.pdf
