### ISSUE TITLE
Radiant Heaters at 2nd floor storefront

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Vacation_Rental#2]
Hi @rvzenteno, in order to counteract cold drafts along the large expanses of glass on the east side of the 2nd floor, we'd like to locate radiant heaters along the base of these windows. 

Are these units we can connect to the water heater, or do they have to have a separated dedicated mini boiler?

If they can be connected to the water heater, I wanted to let you know, just so you can size the water heater appropriately.

@shree6984, @ Let me know if you'd like to add anything. 

Cheers, Ryan

**Comment by rvzenteno** [comment]
Hi @theoryshaw , I have not done anything with radiant heat before and I would not know how to size the water heater for it, that typically is handled by the HVAC contractor/engineer. Researching a bit on this they will need to have a dedicated Hydronic Heating Boiler.  Thanks.

**Comment by theoryshaw** [comment]
Thanks Roberto.  

@shree6984 is this something you guys can handle? or should I ping someone in to help? 

Thanks, Ryan

**Comment by shree6984** [comment]
@rvzenteno Could you please tell what will be outlet water temp for planned domestic water heater . @theoryshaw We are planning to use same water heater for radiator some like this, Please take a look at it https://www.youtube.com/watch?v=50ufVwINeyk

**Comment by rvzenteno** [comment]
The outlet temperature is typically set at 120 F, some places like it hotter like 140 F. But, so people don't get scalded I typically show it at 120 F. @theoryshaw @shree6984

**Comment by rvzenteno** [comment]
@theoryshaw Do they allow PEX piping in WI? Let me know. Otherwise I'll just remove any notes that I have in reference to PEX Piping. 

Thanks,

Roberto,

**Comment by theoryshaw** [comment]
FYI, i was only thinking of isolated baseboard radiator like this at the foot of the 2nd floor storefront: http://www.theradiatorfactory.com/en/radiators/micro-canal

...**not** radiant tubing in the floor.

**Comment by rvzenteno** [comment]
@theoryshaw, I see. The PEX I was asking was for Fixtures though.

**Comment by theoryshaw** [comment]
oh.  I believe they do.
https://docs.legis.wisconsin.gov/search/results?q=Crosslinked&filter=doctype%3Aadministrativecode&filter=agency%3A%22Department+of+Safety+and+Professional+Services+%28SPS%29%22&filter=related_chapter_groups_ss%3A%22Chs.+SPS+301-+%3B+Safety%2C+Buildings%2C+and+Environment%22

But please verify.

If you can, please start a new github issue for different topics. Just to avoid potential confusion. Thanks!

**Comment by shree6984** [comment]
@theoryshaw How abt electrical heater ??? Is it too costly ??

**Comment by shree6984** [comment]
@rvzenteno If you can provide outlet water temp from water heater I will provide hot water capacity required from water heater

**Comment by rvzenteno** [comment]
I was calculating the load for the Water heater and the correct temperature. The Tank Capacity for all the bathrooms, kitchen, Cloth Water, Service sink, and we'll need a 100 Gallon Water heater tank. The temperature will need to be at 140 F. I have to retract my previews comment on the temperature of 120 F.

**Comment by theoryshaw** [comment]
Yes, good call. Let's go with electric. Thx.
