### ISSUE TITLE
Outdoor Patio effect on HVAC

### ISSUE THREAD

**Issue by shree6984** [OpeningDesign/Vacation_Rental#20]
What is the possibility that Patio, Dining room and all bedrooms will be occupied at same time ???

Capacity of HVAC system to be changed but if we can consider outdoor patio into diversity then impact will be minimal. Accordingly there will be addition of 2 grills ( now only 1 is shown).

**Comment by theoryshaw** [comment]
A pretty good chance at Patio, Dining room, & Living room will be occupied at the same time. 

A very low chance the bedrooms and Patio, Dining room, & Living room will be occupied at the same time.

**Comment by shree6984** [comment]
Great !!! Thanks for the input
