### ISSUE TITLE
1st floor Toilet Ventilation plan changed ??

### ISSUE THREAD

**Issue by shree6984** [OpeningDesign/Vacation_Rental#21]
![image](https://user-images.githubusercontent.com/23243475/29288527-b0d6161a-8156-11e7-868f-b61353a925ad.png)

![image](https://user-images.githubusercontent.com/23243475/29288448-6ab8b35e-8156-11e7-944e-bf8830d79b0b.png)

**Comment by theoryshaw** [comment]
I'm not sure why you see that.  When I open the HVAC file, i see...

![image](https://user-images.githubusercontent.com/507113/29289460-2a9d4ffe-8102-11e7-93c2-d9f9ff0be3dd.png)

**Comment by shree6984** [comment]
Some issue .. not sure
