### ISSUE TITLE
Wall mounted exhaust ????

### ISSUE THREAD

**Issue by shree6984** [OpeningDesign/Vacation_Rental#23]
![image](https://user-images.githubusercontent.com/23243475/29381329-6961c284-82e6-11e7-81ac-2b4033bd04dd.png)

These fans are designed for horizontal installation in ceiling .. For vertical installation we need to select other model !!! Advice what is suggested...

**Comment by theoryshaw** [comment]
you can keep as is.  I'll work with the contractor to find one that can be wall mounted.

**Comment by shree6984** [comment]
Ok .. I will also try to get few suggestions on the model ..
