### ISSUE TITLE
Basement cutout/opening

### ISSUE THREAD

**Issue by shree6984** [OpeningDesign/Vacation_Rental#5]
@theoryshaw Could you pls confirm cutout size in basement. I can see a wall cutout on West wall of 1'x7' in dimension . Pls confirm.

If we have cutout then pls confirm if it is directly open or covered with louver ?? 

If covered with louver confirm if it is wooden or metal louver 

Thanks

**Comment by theoryshaw** [comment]
Hi Shree, i'm not sure what you're referring to here?  Can you do a screen capture of the area you're talking about?

**Comment by theoryshaw** [comment]
Closing... please let me know if you'd like to continue the convo.
