### ISSUE TITLE
No insulation at ducts

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Vacation_Rental#6]
No need for insulation at ducts.
Typical throughout.

![image](https://cloud.githubusercontent.com/assets/507113/25584440/9d190e1e-2e5b-11e7-8f86-e5464e2a4535.png)

**Comment by shree6984** [comment]
If duct is in conditioned area we can get away with insulation. But this final call on routing shall be verified by HVAC contractor.
