### ISSUE TITLE
vent in directly from spiral - no flex duct.

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Vacation_Rental#9]
Can we supply these rooms directly off the main branch? That is, no flex duct..

![image](https://cloud.githubusercontent.com/assets/507113/25584745/e0cb356e-2e5c-11e7-81d9-2aae10b5a03c.png)

![revit_2017-05-01_11-15-33](https://cloud.githubusercontent.com/assets/507113/25585325/9346d4d0-2e5f-11e7-9e2b-bf80f24a580f.png)

**Comment by shree6984** [comment]
Done.. This was done to avoid discharge of air from higher distance
